base:
  random_state: 42
  target_column: category

data_source:
  gcs_bucket: youtube-sentiment-data
  file_name: reddit_preprocessing.csv

vectorizer:
  name: TfidfVectorizer
  params:
    ngram_range: [1, 3]
    max_features: 10000

resampling:
  name: SMOTE
  params:
    random_state: 42

model:
  name: LightGBM
  params:
    objective: 'multiclass'
    metric: 'multi_logloss'
    n_estimators: 1200
    learning_rate: 0.05
    num_leaves: 150
    random_state: 42
